exam/urls.py
from django.urls import path
from exam.views import (
    ManageExamsView,
    EditQuestionsListView,
    EditQuestionsUpdateView,
    EditQuestionsDeleteView,
    ManageAnswersListView,
    ManageAnswersUpdateView,
    ManageAnswersDeleteView,
    EditExamsListView,
    EditExamsUpdateView,
    EditExamsDeleteView,
    EditExamsDetailView,
    ExamFormView,
    ActiveExamsListView,
    PreExamTemplateView,
    ExamsListView,
    ExamReviewDetailView,
    ArchivedExamsListView,
    PostExamTemplateView
    )

urlpatterns = [
    path("", ExamFormView.as_view(), name='exam-view'),
    path("notice/", PreExamTemplateView.as_view(), name='exam-notice'),
    path("done", PostExamTemplateView.as_view(), name='exam-done'),
    path('manage/', ManageExamsView.as_view(), name='exam-manage-exams'),
    path('manage/questions', EditQuestionsListView.as_view(), name='exam-edit-questions'),
    path('manage/questions/<int:pk>/update/', EditQuestionsUpdateView.as_view(), name='exam-edit-questions-update'),
    path('manage/questions/<int:pk>/delete/', EditQuestionsDeleteView.as_view(), name='exam-edit-questions-delete'),
    path('manage/questions/<int:pk>/answers/', ManageAnswersListView.as_view(), name='exam-manage-answers'),
    path('manage/questions/<int:pk>/answers/<int:aid>/update/', ManageAnswersUpdateView.as_view(), name='exam-manage-answers-update'),
    path('manage/questions/<int:pk>/answers/<int:aid>/delete/', ManageAnswersDeleteView.as_view(), name='exam-manage-answers-delete'),
    path('manage/exams/', EditExamsListView.as_view(), name='exam-edit-exams'),
    path('manage/exams/<int:pk>/update/', EditExamsUpdateView.as_view(), name='exam-edit-exams-update'),
    path('manage/exams/<int:pk>/delete/', EditExamsDeleteView.as_view(), name='exam-edit-exams-delete'),
    path('manage/exams/<int:pk>/view/', EditExamsDetailView.as_view(), name='exam-edit-exams-view'),
    path('manage/active/', ActiveExamsListView.as_view(), name='exam-active'),
    path('manage/archive/', ArchivedExamsListView.as_view(), name='exam-archive'),
    path('list', ExamsListView.as_view(), name='exams-view'),
    path('list/<int:pk>/view', ExamReviewDetailView.as_view(), name='exams-review'),
]

ind_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('users/<int:pk>/settings/', user_views.UserSettingsUpdateView.as_view(), name='users-settings'),
    path('manage_users/<int:pk>/settings/', user_views.UserSettingsAdminUpdateView.as_view(), name='users-manage-settings'),
    path('exam/', include('exam.urls')),
    path('', include('main.urls'))
]

exam/models.py
from django.db import models
from safedelete.models import SafeDeleteModel, SOFT_DELETE_CASCADE
from users.models import User
from django.utils import timezone


class Question(SafeDeleteModel, models.Model):
    _safedelete_policy = SOFT_DELETE_CASCADE
    question = models.CharField(max_length=2048)
    question_type = models.IntegerField()
    category = models.IntegerField()
    point_value = models.IntegerField()
    creation_date = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return f'{self.question}'


class Answer(SafeDeleteModel, models.Model):
    _safedelete_policy = SOFT_DELETE_CASCADE
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField(max_length=2048)
    correct = models.BooleanField(default=None)
    def __str__(self):
        return f'{self.question} - {self.answer}'

class ExamTemplate(SafeDeleteModel, models.Model):
    _safedelete_policy = SOFT_DELETE_CASCADE
    exam_name = models.CharField(max_length=64)
    questions_one = models.ManyToManyField(Question, related_name="rev_question_one", blank=True)
    questions_two = models.ManyToManyField(Question, related_name="rev_question_two", blank=True)

    def __str__(self):
        return self.exam_name

class Exam(models.Model):
    _safedelete_policy = SOFT_DELETE_CASCADE
    exam_template = models.ForeignKey(ExamTemplate, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    date_sent = models.DateTimeField(auto_now_add=True, blank=True)
    expired = models.BooleanField(default=False, blank=True)
    marked = models.BooleanField(default=False, blank=True)
    reviewed = models.BooleanField(default=False, blank=True)
    passed = models.BooleanField(default=False, blank=True)
    archived = models.BooleanField(default=False, blank=True)
    turned_in = models.DateTimeField(default=None, blank=True, null=True)
    key = models.CharField(max_length=15)
    points = models.IntegerField(default=0)
    points_open_response = models.IntegerField(default=0)
    handler = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    marked_by = models.CharField(max_length=64, blank=True, default=None, null=True)
    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.turned_in}"

class Response(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True)
    open_response = models.TextField(max_length=2048, blank=True)
    correct = models.BooleanField(default=True, blank=True)
    review = models.TextField(max_length=2048, blank=True)
    open_response_points = models.IntegerField(default=0, blank=True)
    def __str__(self):
        return f"{self.exam}"

exam/views.py
from collections import Counter
from json import loads 

from django.shortcuts import redirect, reverse, get_object_or_404, render
from django.views.generic import TemplateView, ListView, DeleteView, FormView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.db.models import F

from main.utils.mixins import UserIsStaffMixin, UserIsSeniorMixin
from exam.forms import ManageQuestionsForm, ManageAnswersForm, ManageExamsForm, ExamForm
from exam.models import Question, Answer, ExamTemplate, Exam, Response
from exam.utils.sections import get_questions
from exam.utils.exam import generate_key





class ManageExamsView(LoginRequiredMixin, UserIsSeniorMixin, TemplateView):
    template_name = 'exam/manage-exams.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context

class EditQuestionsListView(LoginRequiredMixin, UserIsStaffMixin, ListView):
    model = Question
    context_object_name = 'question_list'
    form = ManageQuestionsForm
    template_name = 'exam/edit-questions.html'
    ordering = ['-creation_date']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('exam-edit-questions')

class EditQuestionsUpdateView(LoginRequiredMixin, UserIsStaffMixin, SuccessMessageMixin, UpdateView):
    model = Question
    form_class = ManageQuestionsForm
    template_name = 'exam/edit-questions-update.html'
    success_message = 'Question updated'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context
    def get_success_url(self):
        return reverse('exam-edit-questions-update', kwargs={'pk': self.kwargs['pk']})
    success_url = get_success_url

class EditQuestionsDeleteView(LoginRequiredMixin, UserIsStaffMixin, DeleteView):
    model = Question
    template_name = 'exam/edit-questions-delete.html'
    success_url = '/exam/manage/questions'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context

class ManageAnswersListView(LoginRequiredMixin, UserIsStaffMixin, ListView):
    model = Answer
    context_object_name = 'answer_list'
    form = ManageAnswersForm
    template_name = 'exam/manage-answers.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        context['question_id'] = self.kwargs['pk']
        context['question_text'] = Question.objects.filter(id=self.kwargs['pk']).first().question
        context['form'] = ManageAnswersForm(pk=self.kwargs['pk'])
        return context

    
    def get_queryset(self): #Need to do this to get a list of answers based on the PK in the url
        question_id = self.kwargs['pk'] #So I get the question ID from the url
        question = Question.objects.filter(id=question_id).first() #Get the first question with that id
        return Answer.objects.filter(question=question).order_by("answer") #And return the answers that have that question

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, pk=self.kwargs['pk'])
        question_id = self.kwargs['pk'] #So I get the question ID from the url
        question = Question.objects.filter(id=question_id).first() #Get the first question with that id
        if form.is_valid():
            new_form = form.save(commit=False) #Using this to populate other fields with data, which is the actual question
            new_form.question = question
            new_form.save()
        return HttpResponseRedirect(self.request.path_info) #Using this since it redirects me to the same page

class ManageAnswersUpdateView(LoginRequiredMixin, UserIsStaffMixin, SuccessMessageMixin, UpdateView):
    model = Answer
    form_class = ManageAnswersForm
    template_name = 'exam/manage-answers-update.html'
    success_message = 'Answer updated'
    allow_empty = False
    def get_form_kwargs(self):
        kwargs = super(ManageAnswersUpdateView, self).get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        context['question_id'] = self.kwargs['pk']
        return context
    def get_success_url(self):
        return reverse('exam-manage-answers-update', kwargs={'pk': self.kwargs['pk'], 'aid':self.kwargs['aid']})
    success_url = get_success_url
    def get_object(self, queryset=None):
        return Answer.objects.get(id=self.kwargs['aid'])

class ManageAnswersDeleteView(LoginRequiredMixin, UserIsStaffMixin, DeleteView):
    model = Answer
    template_name = 'exam/manage-answers-delete.html'
    pk_url_kwarg = 'aid'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        context['question_id'] = self.kwargs['pk']
        return context
    def get_success_url(self, **kwargs):
        return reverse_lazy('exam-manage-answers', kwargs={'pk': self.kwargs['pk']})

class EditExamsListView(LoginRequiredMixin, UserIsStaffMixin, ListView):
    model = ExamTemplate
    context_object_name = 'exam_list'
    form = ManageExamsForm
    template_name = 'exam/edit-exams.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
        return redirect('exam-edit-exams')

class EditExamsUpdateView(LoginRequiredMixin, UserIsStaffMixin, SuccessMessageMixin, UpdateView):
    model = ExamTemplate
    form_class = ManageExamsForm
    template_name = 'exam/edit-exams-update.html'
    success_message = 'Exam updated'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context
    def get_success_url(self):
        return reverse('exam-edit-exams-update', kwargs={'pk': self.kwargs['pk']})  
    success_url = get_success_url
    def get_form_kwargs(self):
        kwargs = super(EditExamsUpdateView, self).get_form_kwargs()
        kwargs['section_one'] = get_questions(0)
        kwargs['section_two'] = get_questions(1)
        return kwargs

class EditExamsDeleteView(LoginRequiredMixin, UserIsStaffMixin, DeleteView):
    model = ExamTemplate
    template_name = 'exam/edit-exams-delete.html'
    success_url = '/exam/manage/exams'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context

class EditExamsDetailView(LoginRequiredMixin, UserIsStaffMixin, DetailView):
    model = ExamTemplate
    context_object_name = 'exam'
    template_name = 'exam/edit-exams-view.html'
    allow_empty = False
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = 'admin'
        return context

class PreExamTemplateView(TemplateView):
    template_name = "exam/pre-exam.html"
    key = None
    
    def get(self, request, *args, **kwargs):
        if 'data' in request.GET:
            self.key = request.GET['data']
            return super().get(request=request, *args, **kwargs) 
        return Http404
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = self.key
        return context

class PostExamTemplateView(TemplateView):
    template_name = "exam/post-exam.html"
        

class ExamFormView(TemplateView):
    template_name = "exam/exam.html"
    model = None
    def get(self, request, *args, **kwargs): #Gets called at the start of the page
        if  'data' in request.GET:  # Checks if there is a GET argument named data
            exam_key = request.GET['data'] #if it is, save it
            requested_exam = get_object_or_404(Exam, key=exam_key, expired=False, passed=False, archived=False, turned_in=None) #Check if there is an exam with that id that is available
            requested_exam_template = requested_exam.exam_template #Get the exam template
            self.model = requested_exam_template #Set the model to the temlate
            current_datetime = timezone.now()
            elapsed = current_datetime - requested_exam.date_sent
            if elapsed.total_seconds() > 172800:
                requested_exam.expired = True
                requested_exam.save()
                raise Http404
            return super().get(request=request, *args, **kwargs) #continue
        raise Http404 #No get argument, 404

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exam'] = self.model
        context['questions_one'] = self.model.questions_one.all()
        context['questions_two'] = self.model.questions_two.all()

        return context

    def post(self, request, *args, **kwargs):
        #Here we get the exam so we can update it later

exam/templates/exam/edit-exams-view.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row no-gutter h-100">
        <div class="col-lg-12 pr-5 format-users-box">
            <div class="format-box h-auto">

                <div class="row no-gutter">
                    <div class="col-md">
                        <a href="{% url 'exam-edit-exams' %}" id="center-menu-back-button" class="center-menu-button">Back</a>
                        <img id="ip-logo-admin" class="ip-logo" src="{%static 'main/images/uvt_logo.png'%}" alt="">
                        <h2 id="ip-admin-text">Visualizing {{exam.exam_name}}</h2>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="row no-gutter h-auto">
                        <div class="container">
                            <hr>
                            <ol>
                                <h4 class="text-center">Multiple Choice</h4>
                                {% for question in exam.questions_one.all %}
                                    <li>
                                        <a class='cool-anchor' href="{% url 'exam-edit-questions-update' question.id %}" target="_blank">{{question}} ({{question.point_value}} pts.)</a>
                                        <ul>
                                        {% for answer in question.answer_set.all %}
                                            <a class='cool-anchor' href="{% url 'exam-manage-answers-update' pk=question.id aid=answer.id %}" target="_blank">
                                                {% if answer.correct %}
                                                    <li style="font-weight: bold; color:green;">{{answer.answer}}</li>
                                                {% else %}
                                                    <li>{{answer.answer}}</li>
                                                {% endif %}
                                            </a>
                                        {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                                <hr>
                                <h4 class="text-center">Open Answers</h4>
                                {% for question in exam.questions_two.all %}
                                <a class='cool-anchor' href="{% url 'exam-edit-questions-update' question.id %}" target="_blank">
                                    <li>
                                        {{question}} ({{question.point_value}} pts.)
                                    </li>
                                </a>
                                    <br>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

exam/templates/exam/exam.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<title>LSPD Exam</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="icon" type="image/png" href="{%static 'main/images/uvt_logo.png'%}">
	<link rel="stylesheet" href="{%static 'main/css/main.css'%}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <div class="container format-box mt-3 pb-1 mb-3">
            <div class="container-fluid">
                <div class="row no-gutter">
                    <div class="container">
                        <div class="col-md">
                            <img class="ip-logo mt-3 mb-3" src="{%static 'main/images/uvt_logo.png'%}" alt="">
                            <h2 id="ip-admin-text">Los Santos Police Department Examination</h2>
                        </div>
                    </div>
                </div>
            </div>  
            <div class="container-fluid">
                <div class="row no-gutter h-auto">
                    <div class="container">
                        <div class="col-md">
                            <br>
                            <ol>
                                <h4 style="margin-left: -40px !important;" class="text-center">Principle, Policy, and Structure</h4>
                                {% for question in questions_one %}
                                        <li>
                                            <p></p>{{question}} ({{question.point_value}} pts.)</p>
                                            <ul style="list-style-type:none;">
                                                {% if question.question_type == 0 %}
                                                <div class="checkbox-group required"> 
                                                    {% else%}
                                                <div class="radio-group required">  
                                                {% endif %}
                                                    {% for answer in question.answer_set.all %}
                                                        <li>
                                                            <label>
                                                                {% if question.question_type == 0 %}
                                                                    <input name="{{question.id}}" type="checkbox" value="{{answer.answer}}">
                                                                {%else%}
                                                                    <input name="{{question.id}}" type="radio" value="{{answer.answer}}">
                                                                {% endif %}
                                                                {{answer.answer}}
                                                            </label>
                                                        </li>
                                                    {% endfor %}
                                                </div>
                                            </ul>
                                        </li>
                                {% endfor %}
                                <hr>
                                <h4 style="margin-left: -40px !important;" class="text-center">Open answer</h4>
                                {% for question in questions_two %}
                                    <li>{{question}} ({{question.point_value}} pts.)</li>
                                    <br>
                                    <textarea required name="{{question.id}}" style="width: 100%; height: 15vw;"></textarea>
                                    <br>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                </div>
                
            </div>
            <button id="submit" type="submit" class="center-menu-button-nr">Submit exam</button>
            
        </div>

    </form>
    

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
<script>
    $("#submit").click(function(e) {

        var complete = true;
        var incomplete_group;
        
        $('div.checkbox-group.required').each(function(i) {

            if($(this).find("input[type=checkbox]:checked").length == 0){
                complete = false;
                $(this).find("label").addClass("exam-field-empty");
                incomplete_group = $(this);
            }
            
        });

        $('div.radio-group.required').each(function(i) {

            if($(this).find("input[type=radio]:checked").length == 0){
                complete = false;
                $(this).find("label").addClass("exam-field-empty");
                incomplete_group = $(this);
            }

        });

        if(complete == false){
            e.preventDefault()
            $([document.documentElement, document.body]).animate({
                scrollTop: incomplete_group.closest("li").offset().top
            }, 1000);
            
        }

    });
    
</script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script src="{% static 'main/js/exam-save-answers.js'  %}"></script>
</body>
</html>

exam/templates/exam/exams-review.html
{% extends "main/base.html" %}
{% load static %}



{% block content %}


<div class="row no-gutter h-100 pb-5">
	<div class="col-lg-12 pr-5 pl-5 format-box-col">
		<div class="format-box h-auto container">

			<div class="row no-gutter">
				<div class="col-md">
					{% if not exam.archived %}
						<a href="{% url 'exams-view' %}" id="center-menu-back-button" class="center-menu-button">Back</a>
					{% else %}
						<a href="{% url 'exam-manage-exams' %}" id="center-menu-back-button" class="center-menu-button">Back</a>
					{% endif %}
					<img class="ip-logo fade-in" src="{%static 'main/images/uvt_logo.png'%}" alt="">
					<h2 id="ip-admin-text">Exam of {{exam.first_name}} {{exam.last_name}} ({{exam.points|add:exam.points_open_response}}/50)</h2>
					<span id="review-grade" style="display: none;">{{exam.points|add:exam.points_open_response}}</span>
					<hr>
				</div>
			</div>
			<div class="row no-gutter h-auto">
				<form method="POST" class="w-100">
					{% csrf_token %}
					<div class="container-fluid">
						<ol class="pl-0">
							<div class="container-fluid">
								{% for response in exam.response_set.all%}
									{% if response.question.question_type == 2 %}
										<li>Applicant answer: </li>
										<p style="white-space: pre-wrap;">{{response.open_response}}</p>
											<p>
											<button class="blue-btn" type="button" data-toggle="collapse" data-target="#{{forloop.counter}}" aria-expanded="false" aria-controls="collapseExample">
												View Question
											</button>
											<button class="blue-btn" type="button" data-toggle="collapse" data-target="#key-{{forloop.counter}}" aria-expanded="false" aria-controls="collapseExample">
												View Marking Key
											</button>
										</p>

										<div class="collapse" id="{{forloop.counter}}">
											<div class="card card-body" style="white-space: pre-wrap;">{{response.question}}</div>
										</div>
										<div class="collapse" id="key-{{forloop.counter}}">
											<div class="mt-1 card card-body" style="white-space: pre-wrap;">{{response.answer.answer}}</div>
										</div>

										{% if user == exam.handler or user.staff or user.admin %}
											{% if not exam.archived %}
												{% if response.open_response|default:""|slice:"-1:" == "S" %}
													<label class="d-block mt-5">Marking:</label>
													<textarea name="review-{{response.id}}" style="width: 100%; height: 7vw;">{{response.review}}</textarea>

													<label class="d-block mt-3">Total points (Out of 3):</label>
													<input class="point-input" min="0", max="3" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
												{% else %}
													<label class="d-block mt-5">Marking:</label>
													<textarea name="review-{{response.id}}" style="width: 100%; height: 12vw;">{{response.review}}</textarea>

													<label class="d-block mt-3">Total points (Out of 20):</label>
													<input class="point-input" min="0", max="20" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
												{%endif%}
											{% else %}
												{% if response.open_response|default:""|slice:"-1:" == "S" %}
												<label class="d-block mt-5">Marking:</label>
												<textarea disabled name="review-{{response.id}}" style="width: 100%; height: 7vw;">{{response.review}}</textarea>

												<label class="d-block mt-3">Total points (Out of 3):</label>
												<input disabled class="point-input" min="0", max="3" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
											{% else %}
												<label class="d-block mt-5">Marking:</label>
												<textarea disabled name="review-{{response.id}}" style="width: 100%; height: 12vw;">{{response.review}}</textarea>

												<label class="d-block mt-3">Total points (Out of 20):</label>
												<input disabled class="point-input" min="0", max="20" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
											{%endif%}
											{% endif %}
										{% else %}
											{% if response.open_response|default:""|slice:"-1:" == "S" %}
												<label class="d-block mt-5">Marking:</label>
												<textarea disabled name="review-{{response.id}}" style="width: 100%; height: 7vw;">{{response.review}}</textarea>

												<label class="d-block mt-3">Total points (Out of 3):</label>
												<input disabled class="point-input" min="0", max="3" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
											{% else %}
												<label class="d-block mt-5">Marking:</label>
												<textarea disbled name="review-{{response.id}}" style="width: 100%; height: 12vw;">{{response.review}}</textarea>

												<label class="d-block mt-3">Total points (Out of 20):</label>
												<input disabled class="point-input" min="0", max="20" type="number" name="points-{{response.id}}" value="{{response.open_response_points}}">
										{%endif%}
										{% endif %}
										<hr>
									{% endif %}
								{% endfor %}

						
								<h1 class="d-flex justify-content-center">Overall statistics</h1>

								<p class="text-center">During this exam, the applicant gathered <i class="compute-final">{{exam.points}}</i> on the multiple choice answers and <i class="compute-final" id="total_points"></i> points in open responses</p>
								<p id="final-grade" class="text-center">Final grade :</p>
								<input name="final-grade" id="final-grade-input" type="hidden">
								{% if not exam.marked %}
									{% if user == exam.handler or user.staff or user.admin %}
										{% if not exam.archived %}
											<button name="mark" class='blue-btn ml-auto mr-auto d-block mt-3' type="submit">Submit marking</button>
										{% endif %}
									{% endif %}
								{% else %}
									{% if user == exam.handler or user.staff or user.admin %}
										{% if not exam.archived %}
											<center>
												<button name="pass" class='center-menu-button-nr d-inline ' type="submit">Pass</button>
												<button name="fail" class='center-menu-button-nr d-inline button-danger' type="submit">Fail</button>
											</center>
										{% endif %}
									{% endif %}
								{% endif %}

							</div>
						</ol>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

{% block javascript %}
<script src="{% static 'main/js/compute-points.js'  %}"></script>
{% endblock %}